### ISSUE TITLE
Carousel: Calculate total allocation

### ISSUE THREAD

**Issue by Weihua4455** [themarshallproject/arpa20220125#25]
In the dataset we received from the Treasury, we only have the amount of money each government in the first trench of funding.

Ideally we need to covey that this is not the total amount of money each place will receive, or use the money from the first trench to calculate what the total allocation would be.

@anastasiajourno remember reading that the total allocation is basically double the amount of the first trench. I'm staring a thread here where we can discuss more.

**Comment by anastasiajourno** [comment]
Unfortunately, it's a little more complicated than simply 50%...

TRANCHING OF FUNDS
Local governments will receive funds in two tranches, with 50% provided beginning in May 2021 and the balance delivered approximately 12 months later. States that have experienced a net increase in the unemployment rate of more than 2 percentage points from February 2020 to the latest available data as of the date of certification will receive their full allocation of funds in a single payment; other states will receive funds in two equal tranches. Governments of U.S. territories will receive a single payment. Tribal governments will receive two payments, with the first payment available in May and the second payment, based on employment data, to be delivered in June 2021.
https://home.treasury.gov/policy-issues/coronavirus/assistance-for-state-local-and-tribal-governments/state-and-local-fiscal-recovery-funds

**Comment by anastasiajourno** [comment]
Here is info which states allocation will be split, and which will come as a single payment
https://home.treasury.gov/system/files/136/split-payments-to-states-public1-508A.pdf

**Comment by Weihua4455** [comment]
Ah of course everything is more complicated.

I think we can merge the two datasets and calculate the totally allocation? Or we can use the current allocation number and say something like ... "Federal funding received so far."

**Comment by Weihua4455** [comment]
I don't think we need this one for the cards anymore.
