### ISSUE TITLE
"Fake" random order

### ISSUE THREAD

**Issue by eads** [themarshallproject/arpa20220125#34]
* Put all the items in priority order based on _our_ judgement (e.g. an order column in the airtable)
* Resort at load time to put the active state at the top, and preserve the order otherwise exactly.
* Increment a counter starting at zero in the randousel.

**Comment by Weihua4455** [comment]
As David and I were going through the "show me another" component, we talked about curate the cards so the readers have a better chance to read some of the spendings we wanted to feature.

And we thought we might just assign orders for the cards. For example, number 1: Columbus County, number 2: $2 million on five computers, etc etc.

@susie-c and @anastasiajourno I would love to discuss this approach with you both more! What do ya think?

**Comment by susie-c** [comment]
That sounds good! I think there are only a handful that we will want to shuffle to the top in that way. 

Assuming we may preserve more than one WTF for some states, would this impact that sorting, or would someone in that state see all of their local cards first? We can also just keep it to one per state, though we really have some overachievers in here who I think deserve the extra opportunity to shine.

**Comment by Weihua4455** [comment]
That's a really good question!

I think the easiest approach/flow would be ...

1. We'll sort everything in airtable, from "You should absolutely see this" to "this is still pretty bananas, but we won't cry if you don't get to this one."

2. When someone opens the story, we'll get their geolocation and show them one project from their state, maybe the one with the highest ranking/order?

3. Then when they hit "show me another," we'll show them the first one in our rank, then the second, then the third etc. Except if their state already is the first one in their list, then we jump to the second one.

This feels like a simple enough cycle that will get the job done & not drive us crazy with super complex logic.

**Comment by Weihua4455** [comment]
Testing Slack + GitHub comment integration here!
