### ISSUE TITLE
IP or domain not in whitelist

### ISSUE THREAD

**Issue by Weihua4455** [themarshallproject/arpa20220125#43]
I ran into this "IP or domain not in whitelist" error when I was trying to resolve this `getGeoIpResponse` promise in `graphic.js`. I think this was an issue some of our readers ran into for BADSTATS, too?

Here's the helper code:

```
function getGeoIpResponse() {
  try {
    return fetch("https://api.ipdata.co/?api-key=57e784ed96304ebca711fd1e634274478813c8463abf89fec086b8ae");
  } catch(err) {
    console.log(err);
  }
}
```

For now I'm going to write a fallback variable for when the geo-location doesn't work. We should investigate this more.

**Comment by eads** [comment]
Running an adblocker?

**Comment by Weihua4455** [comment]
Yes but it was still there after I paused the adblocker

**Comment by eads** [comment]
Also, did it fall through to the console.log or trigger an error? That try/except is SUPPOSED to prevent against that causing downstream bugs but clearly it isn't.

**Comment by Weihua4455** [comment]
Oh interesting — turns out I have BADSTATS and ARPA both running with gulp locally. This problem was resolved after I shutdown the BADSTATS localhost.

**Comment by eads** [comment]
Ohhh I know. This is spurious and you can close, though it's a weird thing that needs to be documented somewhere: Only localhost:3000 is whitelisted in the geoip service. Call it when it's being served up from another port on localhost and you'll get an error.

**Comment by Weihua4455** [comment]
Huh!! That's so interesting. Oh web development! Maybe we need a "weird issue people ran into" in Coda?

Closing this ticket!
