### ISSUE TITLE
Randousel edits, round 1

### ISSUE THREAD

**Issue by eads** [themarshallproject/arpa20220125#51]
- [x] Show me another button: Bigger, bolder, outside the main "card" area. Don't worry about desktop, make it look awesome and so clickable on mobile.
- [ ] Footnote needs to explain budget/obligation logic if implemented.
- [x] Add category, it seems interesting

**Comment by Weihua4455** [comment]
Fixed with the excepting of footnote, which will become a nerdbox at the bottom of the story. See #54
